compose recipe: clickhouse and dagster
ClickHouse/examples pull request #106
Opened 2024-03-06 09:18 UTC by slavanorm

minimal example of working dagster + clickhouse.

see readme.md for details

2024-03-06 13:35 UTC, nellicus commented on docker-compose-recipes/recipes/ch-and-dagster/docker-compose.yaml
> +  # todo: for production, set up dagster-webserver and the dagster-daemon
since these recipes are provided AS IS just to provide a quick and dirty test env, it'd be preferable not to suggest production usage

2024-03-06 13:45 UTC, nellicus commented on docker-compose-recipes/recipes/ch-and-dagster/docker-compose.yaml
> +      - network1
```suggestion
```

to keep this  consistent with the other recipes, we can let the default network config take place and remove the `networks` sections altogether, which would yield:

```
➜  ch-and-dagster git:(main) ✗ docker network ls 
NETWORK ID     NAME                     DRIVER    SCOPE
d63430ccfe2c   ch-and-dagster_default   bridge    local
```


Or is there a specific reason for explicitly defining one?

2024-03-06 13:45 UTC, nellicus commented on docker-compose-recipes/recipes/ch-and-dagster/docker-compose.yaml
> +      - network1
```suggestion
```

following above comment on `network` section

2024-03-06 13:46 UTC, nellicus commented on docker-compose-recipes/recipes/ch-and-dagster/docker-compose.yaml
> +    name: network1
```suggestion
```

following above comment on `network` section

2024-03-06 13:47 UTC, nellicus requested changes
Thanks so much for preparing this 🙏 !

Added comments re use of explicit `network` section and production aspects

2024-03-07 07:26 UTC, slavanorm commented
thank you for review. resolved comments

2024-03-07 08:24 UTC, nellicus approved these changes
LGTM ✅

2024-03-08 09:35 UTC, merged