[docker-compose-recipes] LDAP and ClickHouse
ClickHouse/examples pull request #30
Opened 2023-07-11 16:22 UTC by nellicus

this PR implements proper setup of LDAP and ClickHouse.

several LDAP users and groups are mapped to clickhouse Roles with different access levels

2023-07-11 16:55 UTC, DanRoscigno commented
wow, this is great to have!

2023-07-11 16:56 UTC, DanRoscigno commented
I will try to test this after the training webinar finishes.

2023-07-11 18:48 UTC, DanRoscigno commented on docker-compose-recipes/recipes/ch-and-openldap/README.md
> +
```suggestion

If you do not have `ldapsearch` on your host you can run it from the openldap container:

```shell
docker compose exec openldap bash -c "ldapsearch  -D 'cn=bob,ou=Users,dc=clickhouse,dc=test' -b'dc=clickhouse,dc=test' -H ldap://localhost:389 -w password"
```

```

2023-07-11 19:00 UTC, DanRoscigno commented on docker-compose-recipes/recipes/ch-and-openldap/README.md
> +CREATE DATABASE sales;
```suggestion
CREATE DATABASE sales_db;
```

2023-07-11 19:02 UTC, DanRoscigno commented on docker-compose-recipes/recipes/ch-and-openldap/README.md
> +CREATE DATABASE development;
```suggestion
CREATE DATABASE development_db;
```

2023-07-11 19:03 UTC, DanRoscigno requested changes
Love it, tested and added comments.  I have not touched `slapd` since 1997, this brought back bad memories :)

2023-07-12 06:46 UTC, nellicus commented on docker-compose-recipes/recipes/ch-and-openldap/README.md
> +CREATE DATABASE development;
pushed changes. FYI this was just the README doc the actual code executing these statements sits in  https://github.com/ClickHouse/examples/pull/30/files#diff-dc21cae1d6a4eaa7975377108a167ea32ed72ab976ebac765eadbb556611ebfd and https://github.com/ClickHouse/examples/pull/30/files#diff-384019e1ea2348ac9f441aa732cac946853041f584102cf929c2d5c14e3bdf3b which I've also changed accordingly

2023-07-12 06:46 UTC, nellicus commented on docker-compose-recipes/recipes/ch-and-openldap/README.md
> +
pushed changes

2023-07-12 13:01 UTC, DanRoscigno approved these changes

2023-07-12 13:02 UTC, merged