add links
ClickHouse/examples pull request #5
Opened 2023-04-18 16:36 UTC by DanRoscigno

2023-04-26 20:49 UTC, nellicus commented on docker-compose-recipes/recipes/cluster_1S_2R_ch_proxy/README.md
> +example in the documentation](https://clickhouse.com/docs/en/architecture/replication), the main difference is that this adds the ClickHouse Proxy.
might be worth highlighting [CH Proxy](https://github.com/contentsquare/chproxy) is a 3rd party product developed and maintained by ContentSquare

2023-04-26 20:51 UTC, nellicus commented on docker-compose-recipes/recipes/cluster_2S_2R_ch_proxy/README.md
> +See the docs for information on terminology, configuration, and testing.
this one also uses CH proxy and same disclaimer as above is worth applying

2023-04-26 20:54 UTC, nellicus commented on docker-compose-recipes/recipes/cluster_2S_2R_ch_proxy/README.md
> +See the docs for information on terminology, configuration, and testing.
also I don't see an update to the README.md related to cluster_2S_1R_ch_proxy

2023-04-26 20:57 UTC, nellicus commented on docker-compose-recipes/recipes/cluster_1S_2R/README.md
> +This Docker compose file deploys a configuration very similar to [this
```suggestion
This Docker compose file deploys a configuration matching [this
```

2023-04-26 20:58 UTC, nellicus commented on docker-compose-recipes/recipes/cluster_1S_2R/README.md
> +This Docker compose file deploys a configuration very similar to [this
up to you, just wanted to point out it is pretty much the same as the architecture in the referenced docs

2023-04-26 21:02 UTC, nellicus commented on docker-compose-recipes/recipes/cluster_2S_1R/README.md
> +example in the documentation](https://clickhouse.com/docs/en/architecture/horizontal-scaling).
```suggestion
This Docker compose file deploys a configuration similar to [this
example in the documentation](https://clickhouse.com/docs/en/architecture/horizontal-scaling) with the main difference being that 3 independent ClickHouse keeper instances are used in this recipe (instead of just one as in the docs).
```

2023-04-26 21:02 UTC, nellicus requested changes
added feedback

2023-05-04 17:47 UTC, nellicus commented
@DanRoscigno I've resolved one conflict on the readme

2023-05-04 18:10 UTC, DanRoscigno commented
added Chproxy links

2023-05-08 14:03 UTC, DanRoscigno commented
@nellicus I think this one is ready for merging

2023-05-08 14:35 UTC, nellicus commented on docker-compose-recipes/recipes/cluster_2S_2R_ch_proxy/README.md
> +See the docs for information on terminology, configuration, and testing.
@DanRoscigno was this one addressed?

2023-05-08 14:37 UTC, nellicus approved these changes
LGTM

2023-05-08 14:38 UTC, merged