cdc with postgresql and clickhouse
ClickHouse/examples pull request #74
Opened 2023-10-25 14:02 UTC by leartbeqiraj1

2023-10-25 14:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/ClickHouse/examples?pullRequest=74) <br/>All committers have signed the CLA.

2023-10-27 12:20 UTC, gingerwizard requested changes
Minor feedback

2023-10-27 12:20 UTC, gingerwizard commented on cdc-postgresql-clickhouse/docker-compose.yml
> +      ADMINER_DEFAULT_DB_NAME: postgres
nit: new line

2023-10-27 12:20 UTC, gingerwizard commented on cdc-postgresql-clickhouse/postgres/init.sql
> +INSERT INTO demo_table2(message) VALUES ('demo2 message2');
maybe some updates and deletes just to show it works

2023-10-27 12:20 UTC, gingerwizard commented on cdc-postgresql-clickhouse/clickhouse/init.sql
> +CREATE MATERIALIZED VIEW demo_table1_mv
We prefer the explicit syntax where the table is create seperately. Its a nit but causes confusion for people.

2023-10-27 14:48 UTC, leartbeqiraj1 commented on cdc-postgresql-clickhouse/docker-compose.yml
> +      ADMINER_DEFAULT_DB_NAME: postgres
Added new line

2023-10-27 14:49 UTC, leartbeqiraj1 commented on cdc-postgresql-clickhouse/clickhouse/init.sql
> +CREATE MATERIALIZED VIEW demo_table1_mv
I've changed to the explicit syntax, now both tables are created separately from the materialized views.

2023-10-27 14:59 UTC, leartbeqiraj1 commented on cdc-postgresql-clickhouse/postgres/init.sql
> +INSERT INTO demo_table2(message) VALUES ('demo2 message2');
I've added some updates. Also there is a "Testing" section in Readme where I explain to the users how to make changes and how to validate them in ClickHouse.

Also, currently the workflow doesn't support the deletion of rows, since it was not necessary for my use case. If you think it's something necessary, I'll look to integrate it.

2023-11-03 12:05 UTC, merged